version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "53306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password

  front:
    build: ./front/
    command: sh -c "npm start"
    volumes:
      - ./front:/front
      - /front/node_modules
    ports:
      - "58080:8080"

  api:
    build: ./api/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/api
    ports:
      - "53000:3000"
    depends_on:
      - db


  nginx:
    image: nginx:1.14-alpine
    ports:
      - "50080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log/nginx:/var/log/nginx
    depends_on:
      - api
